// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cjavgevepvyhcaeoeido.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqYXZnZXZlcHZ5aGNhZW9laWRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMDAwNjMsImV4cCI6MjA2ODU3NjA2M30.rK5evqS_fO5Tg8M8l3aMiFKMXQfHqhR1ZgyE0vybh6s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});